#----------------------------------------------
# Root Terragrunt config (single file). Reads values/defaults.hcl.
# Cloud-specific provider and backend are inlined below from CLOUD_PROVIDER (env: default azure).
#
# When run from repo root: runs resource-scope module for current CLOUD_PROVIDER.
# When included by children: provides shared locals, provider, remote_state, inputs.
# To run all foundation: terragrunt run-all plan --terragrunt-working-dir 0-foundation
#----------------------------------------------
locals {
  repo_root      = get_repo_root()
  cloud_provider = length(trimspace(get_env("CLOUD_PROVIDER", ""))) > 0 ? trimspace(get_env("CLOUD_PROVIDER", "")) : error("CLOUD_PROVIDER environment variable must be set (e.g. azure or gcp)")
  at_repo_root   = get_terragrunt_dir() == local.repo_root

  # Set TG_USE_LOCAL_BACKEND=1 (or true) to use local state for all modules — no remote backend, no state download. Useful for testing.
  use_local_backend = get_env("TG_USE_LOCAL_BACKEND", "0") != "0"

  default_locals = read_terragrunt_config("${local.repo_root}/values/defaults.hcl").locals

  # Azure: ARM_SUBSCRIPTION_ID, ARM_TENANT_ID only read when cloud_provider is azure (inside branch below). GCP: uses ADC.
  cloud_locals = local.cloud_provider == "gcp" ? {
    cloud_provider  = "gcp"
    provider_block = <<-EOT
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0.0"
    }
  }
}

provider "google" {
  # Use Application Default Credentials (gcloud auth application-default login)
  # or set GOOGLE_APPLICATION_CREDENTIALS.
}
EOT
  } : {
    cloud_provider  = "azure"
    provider_block = <<-EOT
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 4.57.0"  # 4.57+ for node_provisioning_profile (Node Auto-Provisioning / NAP)
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = "${get_env("ARM_SUBSCRIPTION_ID")}"
  tenant_id       = "${get_env("ARM_TENANT_ID")}"
}
EOT
  }

  merged = merge(local.default_locals, local.cloud_locals)

  # Provider block comes from values/<cloud>/defaults.hcl so only the active cloud's
  # config is loaded (no Azure subscription_id/tenant_id when CLOUD_PROVIDER=gcp).
  effective_provider_content = try(local.merged.provider_block, "")

  # When at repo root: flatten merged so resource_scope fields (create, name) are at top level and pass as-is.
  flattened = merge(local.merged, local.merged.resource_scope)
}

# Default: run resource-scope from repo root. Children override with their own source.
terraform {
#  source = local.at_repo_root ? "0-foundation/0-resource_scope/${local.cloud_provider}" : "."
#   source = local.at_repo_root ? "0-foundation/1-vnet/${local.cloud_provider}" : "."
    source = local.at_repo_root ? "0-foundation/2-terraform_state_blob_storage/${local.cloud_provider}" : "."
}

# Remote state: config from values/defaults.hcl tfstate + resource_scope; backend type by CLOUD_PROVIDER.
# Applies to all modules that include this root (e.g. 1-platform/0-*, 0-foundation/*, 2-app/*).
# path_relative_to_include() gives each module its own state key/prefix. Use TG_USE_LOCAL_BACKEND=1 for local state.
remote_state {
  backend = (local.use_local_backend || local.at_repo_root) ? "local" : (local.cloud_provider == "gcp" ? "gcs" : "azurerm")
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = (local.use_local_backend || local.at_repo_root) ? {
    path = "terraform.tfstate"
  } : (local.cloud_provider == "gcp" ? merge(
    { bucket = local.merged.tfstate.bucket_name },
    { prefix = "${local.merged.env_name}/${local.merged.region}/${path_relative_to_include()}" }
  ) : merge(
    {
      resource_group_name  = local.merged.resource_scope.name
      storage_account_name = local.merged.tfstate.bucket_name
      container_name       = local.merged.tfstate.bucket_name
    },
    { key = "${local.merged.env_name}/${local.merged.region}/${path_relative_to_include()}/terraform.tfstate" }
  ))
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = local.effective_provider_content
}

generate "tagging" {
  path      = "zz_autogenerated_tags.tf"
  if_exists = "overwrite"

  contents = <<EOF
    variable "common_tags" {
      type = map(string)
    }

    variable "tag_globals" {
      type = map(string)
    }

    variable "tag_context" {
      type    = map(string)
      default = {}
    }

    locals {

      tag_context = merge(
        var.tag_globals,
        var.tag_context
      )

      rendered_tags = {
        for k, v in var.common_tags :
        k => replace(
          v,
          "/#\\{([^}]+)\\}/",
          lookup(local.tag_context, regex("#\\{([^}]+)\\}", v)[0], "")
        )
      }
    }    
    EOF
}

# When at repo root we run resource-scope module; pass merged config with resource_scope flattened to top level.
# Otherwise children include root and set their own inputs.
inputs = merge(
  local.merged,
  {
    tag_globals = {
# Add anything else that need to be used in the template for common_tags defined in values/defaults.hcl      
      environment = local.merged.env_name
      resource_group = local.merged.resource_scope.name
      region      = local.merged.region
      org         = local.merged.org_name
    }
    tag_context = {
      resource_name = local.merged.resource_scope.name
    }
  }
)
