#----------------------------------------------
# Root Terragrunt config (single file). Reads values/defaults.hcl and
# values/<CLOUD_PROVIDER>/defaults.hcl (env: CLOUD_PROVIDER, default: azure).
#
# When run from repo root: runs resource-scope module for current CLOUD_PROVIDER.
# When included by children: provides shared locals, provider, remote_state, inputs.
# To run all foundation: terragrunt run-all plan --terragrunt-working-dir 0-foundation
#----------------------------------------------
locals {
  repo_root      = get_repo_root()
  cloud_provider = get_env("CLOUD_PROVIDER")
  at_repo_root   = get_terragrunt_dir() == local.repo_root

  # Set TG_USE_LOCAL_BACKEND=1 (or true) to use local state for all modules — no remote backend, no state download. Useful for testing.
  use_local_backend = get_env("TG_USE_LOCAL_BACKEND", "0") != "0"

  default_locals = read_terragrunt_config("${local.repo_root}/values/defaults.hcl").locals
  cloud_locals   = read_terragrunt_config("${local.repo_root}/values/${local.cloud_provider}/defaults.hcl").locals

  merged = merge(local.default_locals, local.cloud_locals)

  # Provider block comes from values/<cloud>/defaults.hcl so only the active cloud's
  # config is loaded (no Azure subscription_id/tenant_id when CLOUD_PROVIDER=gcp).
  effective_provider_content = try(local.merged.provider_block, "")

  # When at repo root: flatten merged so resource_scope fields (create, name) are at top level and pass as-is.
  flattened = merge(local.merged, local.merged.resource_scope)
}

# Default: run resource-scope from repo root. Children override with their own source.
terraform {
#  source = local.at_repo_root ? "0-foundation/0-resource_scope/${local.cloud_provider}" : "."
#   source = local.at_repo_root ? "0-foundation/1-vnet/${local.cloud_provider}" : "."
    source = local.at_repo_root ? "0-foundation/2-terraform_state_blob_storage/${local.cloud_provider}" : "."
}

# Remote state: config from values/defaults.hcl tfstate + resource_scope; backend type by CLOUD_PROVIDER.
# (Terragrunt allows only one level of include, so this cannot live in values/<cloud>/backend.hcl.)
# Use TG_USE_LOCAL_BACKEND=1 to force local backend for all modules (no remote state, for testing).
remote_state {
  backend = (local.use_local_backend || local.at_repo_root) ? "local" : (coalesce(local.cloud_provider, "azure") == "gcp" ? "gcs" : "azurerm")
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = (local.use_local_backend || local.at_repo_root) ? {
    path = "terraform.tfstate"
  } : (coalesce(local.cloud_provider, "azure") == "gcp" ? merge(
    { bucket = local.merged.tfstate.bucket_name },
    { prefix = "${local.merged.env_name}/${local.merged.region}/${path_relative_to_include()}" }
  ) : merge(
    {
      resource_group_name  = local.merged.resource_scope.name
      storage_account_name = local.merged.tfstate.bucket_name
      container_name       = local.merged.tfstate.bucket_name
    },
    { key = "${local.merged.env_name}/${local.merged.region}/${path_relative_to_include()}/terraform.tfstate" }
  ))
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = local.effective_provider_content
}

generate "tagging" {
  path      = "zz_autogenerated_tags.tf"
  if_exists = "overwrite"

  contents = <<EOF
    variable "common_tags" {
      type = map(string)
    }

    variable "tag_globals" {
      type = map(string)
    }

    variable "tag_context" {
      type    = map(string)
      default = {}
    }

    locals {

      tag_context = merge(
        var.tag_globals,
        var.tag_context
      )

      rendered_tags = {
        for k, v in var.common_tags :
        k => replace(
          v,
          "/#\\{([^}]+)\\}/",
          lookup(local.tag_context, regex("#\\{([^}]+)\\}", v)[0], "")
        )
      }
    }    
    EOF
}

# When at repo root we run resource-scope module; pass merged config with resource_scope flattened to top level.
# Otherwise children include root and set their own inputs.
inputs = merge(
  local.merged,
  {
    tag_globals = {
# Add anything else that need to be used in the template for common_tags defined in values/defaults.hcl      
      environment = local.merged.env_name
      resource_group = local.merged.resource_scope.name
      region      = local.merged.region
      org         = local.merged.org_name
    }
    tag_context = {
      resource_name = local.merged.resource_scope.name
    }
  }
)
