#----------------------------------------------
# Root Terragrunt config (single file). Reads values/defaults.hcl and
# values/<CLOUD_PROVIDER>/defaults.hcl (env: CLOUD_PROVIDER, default: azure).
#
# When run from repo root: runs resource-scope module for current CLOUD_PROVIDER.
# When included by children: provides shared locals, provider, remote_state, inputs.
# To run all foundation: terragrunt run-all plan --terragrunt-working-dir 0-foundation
#----------------------------------------------
locals {
  repo_root      = get_repo_root()
  cloud_provider = get_env("CLOUD_PROVIDER")
  at_repo_root   = get_terragrunt_dir() == local.repo_root

  default_locals = read_terragrunt_config("${local.repo_root}/values/defaults.hcl").locals
  cloud_locals   = read_terragrunt_config("${local.repo_root}/values/${local.cloud_provider}/defaults.hcl").locals

  merged = merge(local.default_locals, local.cloud_locals)

  tfstate_storage_account_name    = "${replace(local.merged.deployment_prefix, "-", "")}tfstate"
  resource_scope_name             = local.merged.resource_scope.name
  tfstate_storage_container_name  = local.merged.tfstate.container_name
  resource_name_prefix            = local.merged.deployment_prefix
  environment                     = local.merged.env_name
  common_tags                     = try(local.merged.common_tags, {})

  azure_backend = {
    resource_group_name  = local.resource_scope_name
    storage_account_name = local.tfstate_storage_account_name
    container_name       = local.tfstate_storage_container_name
    key                  = "${local.merged.env_name}/${local.merged.region}/${path_relative_to_include()}/terraform.tfstate"
  }

  # GCP GCS backend: bucket from values or default; prefix built from path
  gcp_tfstate_bucket = coalesce(try(local.merged.tfstate_bucket, ""), "${replace(local.merged.deployment_prefix, "-", "")}tfstate")
  gcp_backend = {
    bucket = local.gcp_tfstate_bucket
    prefix = "${local.merged.env_name}/${local.merged.region}/${path_relative_to_include()}"
  }

  # Remote state: from values/azure or values/gcp. 0-resource_scope and 1-terraform_state_* override to local in their terragrunt.hcl.
  remote_state_backend = try(local.merged.remote_state.backend, "azurerm")
  remote_state_config  = local.remote_state_backend == "gcs" ? local.gcp_backend : local.azure_backend

  # Provider block comes from values/<cloud>/defaults.hcl so only the active cloud's
  # config is loaded (no Azure subscription_id/tenant_id when CLOUD_PROVIDER=gcp).
  effective_provider_content = try(local.merged.provider_block, "")

  # When at repo root: flatten merged so resource_scope fields (create, name) are at top level and pass as-is.
  flattened = merge(local.merged, local.merged.resource_scope)
}

# Default: run resource-scope from repo root. Children override with their own source.
terraform {
#  source = local.at_repo_root ? "0-foundation/0-resource_scope/${local.cloud_provider}" : "."
    source = local.at_repo_root ? "0-foundation/1-vnet/${local.cloud_provider}" : "."
#   source = local.at_repo_root ? "0-foundation/2-terraform_state_blob_storage/${local.cloud_provider}" : "."
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = local.effective_provider_content
}

# Remote state: backend and config from values/<cloud>/defaults.hcl (azure -> azurerm, gcp -> gcs).
# 0-resource_scope and 1-terraform_state_* override to local in their terragrunt.hcl (bootstrap chicken-egg).
remote_state {
  backend = local.at_repo_root ? "local" : local.remote_state_backend
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = local.at_repo_root ? {
    path = "terraform.tfstate"
  } : (local.remote_state_backend == "gcs" ? {
    bucket = local.remote_state_config.bucket
    prefix = local.remote_state_config.prefix
  } : {
    resource_group_name  = local.remote_state_config.resource_group_name
    storage_account_name = local.remote_state_config.storage_account_name
    container_name       = local.remote_state_config.container_name
    key                  = local.remote_state_config.key
  })
}

generate "tagging" {
  path      = "zz_autogenerated_tags.tf"
  if_exists = "overwrite"

  contents = <<EOF
    variable "common_tags" {
      type = map(string)
    }

    variable "tag_globals" {
      type = map(string)
    }

    variable "tag_context" {
      type    = map(string)
      default = {}
    }

    locals {

      tag_context = merge(
        var.tag_globals,
        var.tag_context
      )

      rendered_tags = {
        for k, v in var.common_tags :
        k => replace(
          v,
          "/#\\{([^}]+)\\}/",
          lookup(var.tag_globals, regex("#\\{([^}]+)\\}", v)[0], "")
        )
      }
    }    
    EOF
}

# When at repo root we run resource-scope module; pass merged config with resource_scope flattened to top level.
# Otherwise children include root and set their own inputs.
inputs = merge(
  local.merged,
  {
    tag_globals = {
# Add anything else that need to be used in the template for common_tags defined in values/defaults.hcl      
      environment = local.merged.env_name
      resource_group = local.merged.resource_scope.name
      region      = local.merged.region
      org         = local.merged.org_name
    }
  }
)
