# Override file (name ends in `_override.tf`): merged with the terraform {} block
# auto-generated by root.hcl into provider.tf. Adds the Datadog provider requirement
# without conflicting with the root's azurerm/google declaration.

terraform {
  required_providers {
    datadog = {
      source  = "DataDog/datadog"
      version = ">= 3.0.0"
    }
  }
}
