# Chart versions and docker image references
# Merged with env.yaml and resources.yaml via helmfile

selector-training:
  chart:
    version: 0.1.0
  values:
    image:
      tag: "0.0.74"

divyam-evaluator:
  chart:
    version: 0.1.0
  values:
    image:
      tag: "0.1.51"

router-controller:
  chart:
    version: 0.1.0
  values:
    image:
      tag: "0.1.184"

divyam-route-selector:
  chart:
    version: 0.1.0
  values:
    image:
      tag: "0.1.55"

altinity-clickhouse-operator:
  chart:
    version: 3.2.1

clickhouse:
  chart:
    version: 0.2.72

strimzi-kafka-operator:
  chart:
    version: 0.45.88

kafka-cluster:
  chart:
    version: 0.1.0

otel-collector:
  chart:
    version: 0.1.0

mysql:
  chart:
    version: 0.1.0

divyam-redis:
  chart:
    version: 0.1.0

superset-postgres:
  chart:
    version: 0.1.0

infinity:
  chart:
    subPath: infinity
    version: 1.4.0
  values:
    image:
      tag: 0.0.76

qdrant:
  chart:
    subPath: qdrant
    version: 0.9.5

external-secrets-operator:
  chart:
    version: 0.10.5

kafka-connect:
  chart:
    version: 0.1.0

superset:
  chart:
    version: 0.15.0

superset-ingress:
  chart:
    version: 0.1.0

divyam-db-upgrades:
  chart:
    version: 0.1.0
