# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "divyam-production-terraform-state-bucket"
    prefix = "preprod__pre-production-project__asia-south1/gcp/gke/"
  }
}
