# Global config and platform provider (Azure)
# Combined with resources.yaml and artifacts.yaml via helmfile

environment: preprod
platform:
  provider: AZURE
  azure:
    keyVaultUri: "https://divyam-bkt-preprod-vault.vault.azure.net/"
    storage_configs:
      container: "divyambktpreprodcontainer"
      storage_account: "divyambktpreprodstorage"
    wif:
      tenantID: "ed5c6a8e-5949-4fbb-a0ec-08dbce5cc47e"
      clientIdMap:
        clickhouse: "2a6bcb62-9de6-4bc9-b76e-0a80e657a0ea"
        divyam-control-plane-exporter: "7d990407-1398-41bb-a695-b6de5b3ef8d7"
        divyam-db-upgrades: "42010f48-953c-4378-b5f6-788991d6483c"
        divyam-e2e-test-runner: "f13cc3dc-5f92-4fc3-9877-2f5765463ce9"
        divyam-evaluator: "3a296ba8-fe73-42f3-9381-b63f97c821f8"
        divyam-route-selector: "06e607dd-c35d-4a27-80dc-495e04254630"
        divyam-router-controller: "4669f61f-67e0-4e95-8e87-4d301210bbea"
        divyam-selector-training: "f5145bc4-f49b-47af-af91-59cd88da9d0d"
        kafka-connect: "5c906999-59a7-4407-b5a4-ec3740d5a73c"
        mysql: "890c19c0-f7cd-430e-aed5-c7a94bed5538"
        superset-postgres: "68b3e694-6e82-4b5b-8985-605d19e4b227"

clusterDomain: ""

imagePullSecretConfig:
  enabled: true
