locals {
  filtered_subnets_to_create = [
    for subnet in var.vnet.subnets : { subnet_name = subnet.subnet_name, subnet = subnet } if subnet.create
  ]
  subnets_to_create = { for pair in local.filtered_subnets_to_create : pair.subnet_name => pair.subnet }

  filtered_subnets_existing = [
    for subnet in var.vnet.subnets : { subnet_name = subnet.subnet_name, subnet = subnet } if !subnet.create
  ]
  subnets_existing = { for pair in local.filtered_subnets_existing : pair.subnet_name => pair.subnet }

  # App Gateway subnets: to create vs existing
  filtered_app_gw_subnets_to_create = [
    for subnet in var.vnet["app_gw_subnet"] : { subnet_name = subnet.subnet_name, subnet = subnet } if subnet.create
  ]
  app_gw_subnets_to_create = { for pair in local.filtered_app_gw_subnets_to_create : pair.subnet_name => pair.subnet }

  filtered_app_gw_subnets_existing = [
    for subnet in var.vnet["app_gw_subnet"] : { subnet_name = subnet.subnet_name, subnet = subnet } if !subnet.create
  ]
  app_gw_subnets_existing = { for pair in local.filtered_app_gw_subnets_existing : pair.subnet_name => pair.subnet }
}

resource "azurerm_virtual_network" "vnet" {
  count               = var.vnet.create ? 1 : 0
  name                = var.vnet.name
  address_space       = var.vnet.address_space
  location            = var.vnet.region
  resource_group_name = var.vnet.scope_name

  tags = local.rendered_tags # Autogenerated via root level terragrunt.hcl

  lifecycle {
    ignore_changes = [
      name
    ]
    prevent_destroy = true
  }
}

# Look up the existing Azure Virtual Network.
data "azurerm_virtual_network" "vnet" {
  count               = var.vnet.create ? 0 : 1
  name                = var.vnet.name
  resource_group_name = var.vnet.scope_name
}

# Look up existing subnets
data "azurerm_subnet" "existing_subnets" {
  for_each             = local.subnets_existing
  name                 = each.key
  virtual_network_name = (var.vnet.create ? azurerm_virtual_network.vnet[0].name : data.azurerm_virtual_network.vnet[0].name)
  resource_group_name  = var.vnet.scope_name
}

# Look up existing App Gateway subnets
data "azurerm_subnet" "existing_app_gw_subnets" {
  for_each             = local.app_gw_subnets_existing
  name                 = each.key
  virtual_network_name = (var.vnet.create ? azurerm_virtual_network.vnet[0].name : data.azurerm_virtual_network.vnet[0].name)
  resource_group_name  = var.vnet.scope_name
}

resource "azurerm_subnet" "subnets" {
  for_each = local.subnets_to_create

  name                 = each.key
  resource_group_name  = var.vnet.scope_name
  virtual_network_name = (var.vnet.create ? azurerm_virtual_network.vnet[0].name : data.azurerm_virtual_network.vnet[0].name)
  address_prefixes     = [each.value.subnet_ip]
  service_endpoints    = ["Microsoft.Storage"]

  lifecycle {
    ignore_changes = [
      name
    ]
    prevent_destroy = true
  }
}

# App Gateway subnets (with Application Gateway delegation)
resource "azurerm_subnet" "app_gw_subnets" {
  for_each = local.app_gw_subnets_to_create

  name                 = each.key
  resource_group_name  = var.vnet.scope_name
  virtual_network_name = (var.vnet.create ? azurerm_virtual_network.vnet[0].name : data.azurerm_virtual_network.vnet[0].name)
  address_prefixes     = [each.value.subnet_ip]
  service_endpoints    = ["Microsoft.Storage"]

  delegation {
    name = "application_gateway_delegation"

    service_delegation {
      name = "Microsoft.Network/applicationGateways"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action"
      ]
    }
  }

  lifecycle {
    ignore_changes = [
      name
    ]
    prevent_destroy = true
  }
}
