# Azure alerts: action group + Prometheus rule groups. Uses config from values/defaults.hcl (alerts) and shared rules from 2-alerts/common/alerts.
# Tags: root generates zz_autogenerated_tags.tf. Per-resource tags so action group and each rule group get their name in tags.

locals {
  alert_files = fileset(var.alerts_folder, "*.json")
  alerts = {
    for f in local.alert_files :
    trimsuffix(basename(f), ".json") => jsondecode(file("${var.alerts_folder}/${f}"))
  }

  tag_context_base = merge(var.tag_globals, var.tag_context)
  action_group_name = "${var.resource_name_prefix}-alerts-action-group"
  rendered_tags_action_group = {
    for k, v in var.common_tags :
    k => replace(v, "/#\\{([^}]+)\\}/", lookup(merge(local.tag_context_base, { resource_name = local.action_group_name }), try(regex("#\\{([^}]+)\\}", v)[0], ""), ""))
  }
  rendered_tags_rule_group = {
    for name, alert in local.alerts :
    name => {
      for k, v in var.common_tags :
      k => replace(v, "/#\\{([^}]+)\\}/", lookup(merge(local.tag_context_base, { resource_name = replace(alert.name, "_", "-") }), try(regex("#\\{([^}]+)\\}", v)[0], ""), ""))
    }
  }
}

resource "azurerm_monitor_action_group" "alerts" {
  name                = local.action_group_name
  resource_group_name = var.resource_group_name
  short_name          = "alerts"

  dynamic "email_receiver" {
    for_each = var.notification_email_alert_email != null && var.notification_email_alert_email != "" ? [var.notification_email_alert_email] : []
    content {
      name          = "email-alert"
      email_address = email_receiver.value
    }
  }

  dynamic "webhook_receiver" {
    for_each = var.notification_pager_webhook_url != null && var.notification_pager_webhook_url != "" ? [var.notification_pager_webhook_url] : []
    content {
      name                    = "pager-webhook"
      service_uri             = webhook_receiver.value
      use_common_alert_schema = true
    }
  }

  dynamic "webhook_receiver" {
    for_each = var.notification_gchat_space_id != null && var.notification_gchat_space_id != "" ? [var.notification_gchat_space_id] : []
    content {
      name                    = "gchat-webhook"
      service_uri             = "https://chat.googleapis.com/v1/spaces/${webhook_receiver.value}/messages"
      use_common_alert_schema = true
    }
  }

  dynamic "webhook_receiver" {
    for_each = var.notification_slack_webhook_url != null && var.notification_slack_webhook_url != "" ? [var.notification_slack_webhook_url] : []
    content {
      name                    = "slack-webhook"
      service_uri             = webhook_receiver.value
      use_common_alert_schema = true
    }
  }

  tags = local.rendered_tags_action_group
}

resource "azurerm_monitor_alert_prometheus_rule_group" "alerts" {
  for_each            = local.alerts
  name                = replace(each.value.name, "_", "-")
  location            = var.location
  resource_group_name = var.resource_group_name
  cluster_name       = var.azure_monitor_workspace_name
  description        = lookup(each.value, "description", each.value.name)
  rule_group_enabled  = lookup(each.value, "enabled", true)
  interval           = each.value.interval
  scopes             = [var.azure_monitor_workspace_id]

  dynamic "rule" {
    for_each = each.value.rules
    content {
      alert   = rule.value.alert
      expression = rule.value.expression
      for    = rule.value.for
      enabled = lookup(rule.value, "enabled", true)

      dynamic "alert_resolution" {
        for_each = lookup(rule.value, "alert_resolution", null) != null ? [1] : []
        content {
          auto_resolved   = rule.value.alert_resolution.auto_resolved
          time_to_resolve = rule.value.alert_resolution.time_to_resolve
        }
      }

      labels = {
        severity   = rule.value.labels.severity
        rule_group = rule.value.labels.rule_group
        alert_rule = rule.value.labels.alert_rule
      }

      annotations = {
        summary     = rule.value.annotations.summary
        description = rule.value.annotations.description
      }

      dynamic "action" {
        for_each = contains(["CRITICAL"], rule.value.labels.severity) ? [1] : []
        content {
          action_group_id = azurerm_monitor_action_group.alerts.id
        }
      }
    }
  }

  tags = local.rendered_tags_rule_group[each.key]
}
