# Override file (name ends in `_override.tf`): merged with the terraform {} block
# auto-generated by root.hcl into provider.tf. Adds the Grafana provider requirement
# (used to push dashboards to Azure Managed Grafana) without conflicting with the
# root's azurerm declaration.

terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = ">= 3.0.0"
    }
  }
}
