#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# This script generates the Terraform/Terragrunt config and secrets file the IaC reads.
#
# This repo's IaC reads ALL configuration via terragrunt `get_env(...)`, there are no .tfvars files.
# The standard way to feed it is the `TF_VAR_*` env-var convention plus the plain config vars.
# This script writes that file as `iac/values/secrets.env`, kept next to the VALUES_FILE (`iac/values/defaults.hcl`).
# `scripts/iac.sh` auto-sources it before running terragrunt, so you never source it by hand.
#
# It fills safe-to-randomize secrets with fresh random values and sets sensible config defaults.
# It leaves real or externally-meaningful values (cloud creds, registry path, webhooks, vendor keys) as PLACEHOLDERS for you to fill in, or passes them through if already exported.
# Real secrets are NEVER randomized.
#
# Usage:
#   scripts/gen-tf-env.sh --cloud gcp --env dev [--region R] [--zone Z] [--out FILE] [--force]
#
# Then just run the workflow, iac.sh loads the file automatically:
#   ./scripts/iac.sh config -c gcp -e dev
#   ./scripts/iac.sh plan -l 0-foundation
#
# The output file is chmod 600 and gitignored (iac/values/secrets.env). DO NOT COMMIT IT.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib/cli.sh
source "$REPO_ROOT/scripts/lib/cli.sh"

CLOUD="gcp"; ENV_NAME="dev"; OUT=""; FORCE=0; REGION_ARG=""; ZONE_ARG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --cloud)  CLOUD="$2"; shift 2;;
    --cloud=*) CLOUD="${1#*=}"; shift;;
    --env)    ENV_NAME="$2"; shift 2;;
    --env=*)  ENV_NAME="${1#*=}"; shift;;
    --region) REGION_ARG="$2"; shift 2;;
    --region=*) REGION_ARG="${1#*=}"; shift;;
    --zone)   ZONE_ARG="$2"; shift 2;;
    --zone=*) ZONE_ARG="${1#*=}"; shift;;
    --out)    OUT="$2"; shift 2;;
    --out=*)  OUT="${1#*=}"; shift;;
    --force)  FORCE=1; shift;;
    -h|--help) cli::usage "$0"; exit 0;;
    *) cli::die "unknown arg: $1 (try --help)";;
  esac
done

OUT="${OUT:-$REPO_ROOT/iac/values/secrets.env}"
cli::validate_enum --cloud "$CLOUD" gcp azure
if [[ -e "$OUT" && "$FORCE" -ne 1 ]]; then
  cli::die "refusing to overwrite existing $OUT (use --force)" 1
fi
mkdir -p "$(dirname "$OUT")"

# random alphanumeric of N chars (avoids shell/connection-string quoting headaches)
rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-32}"; echo; }
uuid() { if command -v uuidgen >/dev/null; then uuidgen | tr 'A-Z' 'a-z'; else cat /proc/sys/kernel/random/uuid; fi; }
# pass through an already-exported env var, else use the given default
passthru() { local n="$1" d="${2:-}"; printf '%s' "${!n:-$d}"; }

# REGION/ZONE: flag > exported env > cloud default. The cloud defaults below are EXAMPLES, edit them or pass --region/--zone for your deployment.
if [[ "$CLOUD" == gcp ]]; then def_region="asia-south1"; def_zone="asia-south1-c"
else                           def_region="centralindia"; def_zone="centralindia-1"; fi
REGION="${REGION_ARG:-$(passthru REGION "$def_region")}"
ZONE="${ZONE_ARG:-$(passthru ZONE "$def_zone")}"

umask 077
{
  echo "# SPDX-License-Identifier: Apache-2.0"
  echo "# generated by gen-tf-env.sh — Terraform/Terragrunt config + secrets. DO NOT COMMIT."
  echo "# cloud=$CLOUD env=$ENV_NAME  |  auto-sourced by scripts/iac.sh"
  echo "# Fill the values marked 'FILL' below; the rest are pre-populated for a sandbox."
  echo

  echo "# --- core config (consumed by iac/values/defaults.hcl via get_env) ---"
  echo "export CLOUD_PROVIDER=$CLOUD"
  echo "export ENV=$ENV_NAME"
  echo "export VALUES_FILE=$(passthru VALUES_FILE "values/defaults.hcl")"
  echo "export REGION=$REGION   # EDIT for your deployment"
  echo "export ZONE=$ZONE   # EDIT for your deployment"
  echo "export ORG_NAME=$(passthru ORG_NAME "")"
  if [[ "$CLOUD" == gcp ]]; then
    echo "export BILLING_ACCOUNT=$(passthru BILLING_ACCOUNT "")   # only if creating a new GCP billing link"
  fi
  echo

  echo "# --- RANDOMIZED: safe for a throwaway env (DB/admin passwords, signing & encryption keys) ---"
  echo "export TF_VAR_divyam_db_root_password=$(rand 24)"
  echo "export TF_VAR_divyam_db_password=$(rand 24)"
  echo "export TF_VAR_divyam_clickhouse_password=$(rand 24)"
  echo "export TF_VAR_divyam_superset_pg_password=$(rand 24)"
  echo "export TF_VAR_divyam_superset_password=$(rand 20)"
  echo "export TF_VAR_divyam_router_admin_password=$(rand 20)"
  echo "export TF_VAR_divyam_jwt_secret_key=$(rand 48)"
  echo "export TF_VAR_divyam_provider_keys_encryption_key=$(rand 44)"
  echo "# evalm8 stack (used when STACK != router). Set the login passwords to known values for a real deploy."
  echo "export TF_VAR_divyam_lakefs_access_key_id=$(rand 20)"
  echo "export TF_VAR_divyam_lakefs_secret_access_key=$(rand 40)"
  echo "export TF_VAR_divyam_lakefs_auth_encrypt_key=$(rand 32)"
  echo "export TF_VAR_divyam_argilla_api_key=$(rand 32)"
  echo "export TF_VAR_divyam_argilla_auth_secret_key=$(rand 32)"
  echo "export TF_VAR_divyam_argilla_default_user_password=$(rand 24)"
  echo "export TF_VAR_divyam_evalm8_jwt_secret=$(rand 48)"
  echo "export TF_VAR_divyam_evalm8_encryption_key=$(LC_ALL=C tr -dc 'a-f0-9' </dev/urandom | head -c 64)"
  echo "export TF_VAR_divyam_evalm8_admin_password="
  echo

  echo "# --- identifiers (non-secret; defaults match the IaC, override if needed) ---"
  echo "export TF_VAR_divyam_db_user=$(passthru TF_VAR_divyam_db_user "divyam")"
  echo "export TF_VAR_divyam_db_name=$(passthru TF_VAR_divyam_db_name "divyam")"
  echo "export TF_VAR_divyam_db_user_name=$(passthru TF_VAR_divyam_db_user_name "divyam-$ENV_NAME")"
  echo "export TF_VAR_divyam_clickhouse_user_name=$(passthru TF_VAR_divyam_clickhouse_user_name "default")"
  echo

  echo "# --- ISSUED BY DIVYAM: random fallback for a standalone sandbox; replace with the real"
  echo "#     values from Divyam if this env must register/authenticate with Divyam's control plane. ---"
  echo "export TF_VAR_divyam_deployment_id=$(passthru TF_VAR_divyam_deployment_id "$(uuid)")"
  echo "export TF_VAR_divyam_deployment_api_key=$(passthru TF_VAR_divyam_deployment_api_key "$(rand 40)")"
  echo

  echo "# --- FILL: real values — passed through from your environment if set, else fill these in. ---"
  if [[ "$CLOUD" == azure ]]; then
    echo "# Private image registry (Azure: REQUIRED to pull Divyam images): PATH to the Divyam GAR"
    echo "# dockerconfigjson file. Stored as a Key Vault secret → image-pull secret. Must be valid JSON."
    echo "export TF_VAR_divyam_artifactory_docker_auth=$(passthru TF_VAR_divyam_artifactory_docker_auth "")"
  else
    echo "# Private image registry: NOT needed on GCP — GKE pulls from GAR via the node/workload service"
    echo "# account (image_pull_secret_enabled is false for GCP). Leave TF_VAR_divyam_artifactory_docker_auth unset."
  fi
  echo "# Cloud credentials:"
  if [[ "$CLOUD" == azure ]]; then
    echo "export ARM_CLIENT_ID=$(passthru ARM_CLIENT_ID "")"
    echo "export ARM_CLIENT_SECRET=$(passthru ARM_CLIENT_SECRET "")"
    echo "export ARM_SUBSCRIPTION_ID=$(passthru ARM_SUBSCRIPTION_ID "")"
    echo "export ARM_TENANT_ID=$(passthru ARM_TENANT_ID "")"
  else
    echo "export GOOGLE_APPLICATION_CREDENTIALS=$(passthru GOOGLE_APPLICATION_CREDENTIALS "")  # SA key path, or use ADC"
  fi
  echo "# Alerting → Zenduty (REQUIRED for the alert loop): comma-separated Zenduty webhook URL(s)"
  echo "export NOTIFICATION_WEBHOOK_URLS=$(passthru NOTIFICATION_WEBHOOK_URLS "")"
  echo "# Optional extra notification channels (leave blank if unused):"
  echo "export NOTIFICATION_EMAIL_ALERT_EMAIL=$(passthru NOTIFICATION_EMAIL_ALERT_EMAIL "")"
  echo "export NOTIFICATION_SLACK_WEBHOOK_URL=$(passthru NOTIFICATION_SLACK_WEBHOOK_URL "")"
  echo "export NOTIFICATION_PAGER_WEBHOOK_URL=$(passthru NOTIFICATION_PAGER_WEBHOOK_URL "")"
  echo "export NOTIFICATION_GCHAT_SPACE_ID=$(passthru NOTIFICATION_GCHAT_SPACE_ID "")"
  echo "# Optional integrations (only when used):"
  echo "export TF_VAR_datadog_api_key=$(passthru TF_VAR_datadog_api_key "")"
  echo "export TF_VAR_datadog_app_key=$(passthru TF_VAR_datadog_app_key "")"
  echo "export TF_VAR_grafana_api_token=$(passthru TF_VAR_grafana_api_token "")   # Azure Managed Grafana dashboards"
  echo "export TF_VAR_divyam_openai_billing_admin_api_key=$(passthru TF_VAR_divyam_openai_billing_admin_api_key "")"
} > "$OUT"

chmod 600 "$OUT"
cli::ok "wrote ${OUT#"$REPO_ROOT"/} (chmod 600). scripts/iac.sh will auto-source it."
# warn about empty REQUIRED reals
if ! grep -q 'NOTIFICATION_WEBHOOK_URLS=..' "$OUT"; then
  cli::warn "NOTIFICATION_WEBHOOK_URLS is empty — set your Zenduty webhook before running the alert loop."
fi
if [[ "$CLOUD" == azure ]] && ! grep -q 'divyam_artifactory_docker_auth=..' "$OUT"; then
  cli::warn "TF_VAR_divyam_artifactory_docker_auth is empty — Azure needs it (a path to the GAR dockerconfigjson file) to pull Divyam images. GCP does not."
fi
