# GCP project (resource scope). Equivalent to Azure resource group.
# Use local backend; project is needed before GCS bucket for state.

# Create project when create = true
resource "google_project" "project" {
  count = var.resource_scope.create ? 1 : 0

  project_id      = var.resource_scope.name
  name            = var.resource_scope.name
  org_id          = var.org_id != "" ? var.org_id : null
  folder_id       = var.folder_id != "" ? var.folder_id : null
  billing_account = var.billing_account != "" ? var.billing_account : null

  # Avoid default VPC; we create Shared VPC in 2-vnet.
  auto_create_network = false

  labels = local.rendered_tags  # Autogenerated via root level terragrunt.hcl

  lifecycle {
    prevent_destroy = true
  }
}

# Look up existing project when create = false
data "google_project" "project" {
  count      = var.resource_scope.create ? 0 : 1
  project_id = var.resource_scope.name
}

locals {
  project = var.resource_scope.create ? google_project.project[0] : data.google_project.project[0]
}
