# Create resource group when create = true
resource "azurerm_resource_group" "rd" {
  count    = var.resource_scope.create ? 1 : 0
  name     = var.resource_scope.name
  location = var.region

  tags = local.rendered_tags  # Autogenerated via root level terragrunt.hcl

  lifecycle {
    prevent_destroy = true
  }
}

# Look up existing resource group when create = false
data "azurerm_resource_group" "rd" {
  count = var.resource_scope.create ? 0 : 1
  name  = var.resource_scope.name
}

locals {
  rg = var.resource_scope.create ? azurerm_resource_group.rd[0] : data.azurerm_resource_group.rd[0]
}