environment: dev

service:
  type: NodePort

resources: { }

persistence:
  accessModes: [ "ReadWriteOnce" ]
  size: 100Gi
  annotations: { }
  # storageVolumeName: qdrant-storage
  storageClassName: divyam-managed-csi

snapshotPersistence:
  accessModes: [ "ReadWriteOnce" ]
  size: 100Gi
  annotations: { }
  # storageVolumeName: qdrant-storage
  storageClassName: divyam-managed-csi