variable "create" {
  description = "Whether to create the bastion host and associated resources"
  type        = bool
  default     = false
}

variable "location" {
  type        = string
  description = "The Azure region where all resources will be deployed (e.g., East US, West Europe)."
}

variable "environment" {
  description = "Deployment environment"
  type        = string
}

# common_tags is provided by root's generate "tagging" (zz_autogenerated_tags.tf) when using Terragrunt
variable "resource_group_name" {
  type        = string
  description = "The name of the existing Azure Resource Group in which to create resources."
}

variable "bastion_name" {
  type        = string
  description = "The name of the Bastion host VM and associated resources (NIC, NSG, etc.)."
}

variable "vm_size" {
  type        = string
  description = "The Azure VM size to use for the Bastion host (e.g., Standard_B1s, Standard_DS1_v2)."
  default     = "Standard_B1s"
}

variable "spot_instance" {
  description = "When true, create a Spot VM (priority Spot); when false, regular on-demand."
  type        = bool
  default     = false
}

variable "admin_username" {
  type        = string
  description = "Admin username for the Bastion VM SSH access."
  default     = "azureuser"
}

variable "ssh_public_key_path" {
  description = "The path to the local SSH public key file to be used for VM login."
  type        = string
  default     = "~/.ssh/id_rsa.pub"
}

variable "vnet_id" {
  description = "ID of the Virtual Network"
  type        = string
}

variable "subnet_ids" {
  description = "Map of subnet resource IDs"
  type        = map(string)
}

variable "subnet_names" {
  description = "List of subnet names"
  type        = list(string)
}

variable "subnet_prefixes" {
  description = "Map of subnet CIDR prefixes"
  type        = map(string)
}

variable "vnet_subnet_name" {
  description = "The name of the subnet to use"
  type        = string
}

variable "cluster_name" {
  description = "Cluster name from k8s section; used when configure_kubectl is true"
  type        = string
  default     = ""
}

variable "configure_kubectl" {
  description = "When true, install kubectl and a setup script to fetch cluster credentials (cluster details from k8s section)"
  type        = bool
  default     = false
}

variable "import_mode" {
  description = "Set to true (e.g. TF_VAR_import_mode=1) when running terraform import so the resource blocks exist; leave false for normal runs."
  type        = bool
  default     = false
}
